# Generated by Django 3.0 on 2019-12-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(null=True, upload_to='media/')),
            ],
        ),
    ]
