# Generated by Django 3.0 on 2019-12-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20191218_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='word',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
