# Generated by Django 3.0 on 2019-12-17 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='record.Word'),
        ),
    ]
