# Generated by Django 3.0 on 2019-12-17 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_entry_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='word',
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='record.Word'),
        ),
    ]
