# Generated by Django 3.0 on 2019-12-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20191214_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='upload',
            field=models.FileField(upload_to='media'),
        ),
    ]
