# Generated by Django 3.0 on 2019-12-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20191214_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='upload',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
