# Generated by Django 3.0 on 2019-12-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20191214_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='upload',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
