# Generated by Django 3.0 on 2019-12-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20191214_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
